### ISSUE TITLE
Got it to work, when Start is called, audioclip is only a second long?

### ISSUE THREAD

**Issue by ymalegao** [bnco-dev/unity-webgl-microphone#2]
I have the Microphone.Start function on a button, so I don't think it is being called before the page is interacted with, would you happen to know why this error happens

**Comment by spandey7117** [comment]
how you fixed this issue, on browser getting only 1 sec long clip

**Comment by bnco-dev** [comment]
Yes, it's mentioned in the readme. I've just set it to a short default (more like 500ms) because I thought people would want to stream the mic rather than record, and it's long enough for that. The `lengthSec` argument is just to keep compatibility with the builtin Microphone class. You can probably extend it to as long as you'd like though by changing the `LENGTH_SAMPLES_MULTIPLIER` constant to something higher. I'll add this in when I get time to test it, but it won't be soon.
